--09
ALTER TABLE Users
DROP CONSTRAINT PK__Users__3214EC07F71AFFA2

ALTER TABLE Users
ADD CONSTRAINT PK_IdUsername PRIMARY KEY (Id, Username)

--10
ALTER TABLE Users
ADD CONSTRAINT CH_PasswordIsAtLeast5Symbols CHECK(LEN(Password) >= 5)

--11
ALTER TABLE Users
ADD CONSTRAINT DF_LastLoginTime DEFAULT  GETDATE() FOR LastLoginTime

--12
ALTER TABLE Users
ADD CONSTRAINT CH_UserNameLength CHECK(LEN(Username) >= 3)

--13
