--CREATE DATABASE Airport

CREATE TABLE Passengers
(
Id INT PRIMARY KEY IDENTITY,
FullName VARCHAR(100) NOT NULL,
Email VARCHAR(50) NOT NULL
)

CREATE TABLE Pilots
(
Id INT PRIMARY KEY IDENTITY,
FirstName VARCHAR(30) NOT NULL UNIQUE,
LastName VARCHAR(30) NOT NULL UNIQUE,
Age TINYINT NOT NULL,
Rating FLOAT,
CHECK(Age >= 21 AND Age <= 62),
CHECK(Rating >= 0.0 AND Rating <= 10.0 )
)

CREATE TABLE AircraftTypes
(
Id INT PRIMARY KEY IDENTITY,
TypeName VARCHAR(30) NOT NULL UNIQUE 
)

CREATE TABLE Aircraft
(
Id INT PRIMARY KEY IDENTITY,
Manufacturer VARCHAR(25) NOT NULL,
Model VARCHAR(30) NOT NULL,
[Year] INT NOT NULL,
FlightHours INT,
Condition CHAR(1) NOT NULL,
TypeId INT NOT NULL REFERENCES AircraftTypes(Id)
)

CREATE TABLE PilotsAircraft
(
AircraftId INT REFERENCES Aircraft(Id),
PilotId INT REFERENCES Pilots(Id)
PRIMARY KEY (AircraftId, PilotId)
)

CREATE TABLE Airports
(
Id INT PRIMARY KEY IDENTITY,
AirportName VARCHAR(70) NOT NULL UNIQUE,
Country VARCHAR(100) NOT NULL UNIQUE,
)

CREATE TABLE FlightDestinations
(
Id INT PRIMARY KEY IDENTITY,
AirportId INT NOT NULL REFERENCES Airports(Id),
[Start] DATETIME NOT NULL,
AircraftId INT NOT NULL REFERENCES Aircraft(Id),
PassengerId INT NOT NULL REFERENCES Passengers(Id),
TicketPrice DECIMAL(18,2) NOT NULL DEFAULT 15
)